version = 1

exclude_patterns = [
  "/examples/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "browser",
    "mocha",
    "nodejs"
  ]
  plugins = ["react"]
  dialect = "typescript"
  dependency_file_paths = [
  "/supabase-ui/"
  ]
